config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users

  # devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  post "/export-excel" => "products#export_excel"

  devise_scope :user do
    root 'devise/sessions#new' 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

	def self.search_product(params)
		query = "id is not null"
    query = query + " and name like '%#{params[:name]}%'" unless params[:name].blank?
    query = query + " and model like '%#{params[:model]}%'" unless params[:model].blank?
    query = query + " and brand like '%#{params[:brand]}%'" unless params[:brand].blank?
    query = query + " and ram like '%#{params[:ram]}%'" unless params[:ram].blank?
    query = query + " and external_storage like '%#{params[:external_storage]}%'" unless params[:external_storage].blank?
    return query
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	  products_path
	end

end

app/controllers/products_controller.rb
require 'csv'
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.where(Product.search_product(params)).paginate(page: params[:page], per_page: 25)
  end

  def export_excel
    if params[:data].present?
      data = JSON params[:data]
      @csv_data = CSV.generate do |csv|
        csv << data.first.keys
        data.each do |t|
          arr = t.values
          arr[0] = '=HYPERLINK("'"https://liquiddiamonds.herokuapp.com/products/#{arr[0]}"'", "'"#{arr[0]}"'")'

            # '=HYPERLINK("http://stackoverflow.com", "so.com")'
          csv << arr
        end
      end
      send_data @csv_data, :type => 'text/xls; charset=iso-8859-1; header=present', :disposition => "attachment; filename=products.xls"
      flash[:notice] = 'File Downloaded'
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :model, :brand, :year, :ram, :external_storage, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiquidDiamondsTest</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
	  <%= link_to('Logout', destroy_user_session_path, method: :get, class: "btn btn-danger") %>        
	<% end %>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :ram %>
    <%= f.text_field :ram %>
  </div>

  <div class="field">
    <%= f.label :external_storage %>
    <%= f.text_field :external_storage %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="col-md-12 p-3 border bg-light">
<h4>Filters :</h4>
<%= form_tag products_path, :method => :get, class: "form-inline" do %>
  <div class="form-group col-md-3">
    <%= text_field_tag :name, params[:name], placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= text_field_tag :brand, params[:brand], placeholder: "Brand", class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= text_field_tag :model, params[:model], placeholder: "Model", class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= text_field_tag :ram, params[:ram], placeholder: "RAM", class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= text_field_tag :external_storage, params[:external_storage], placeholder: "External Storage", class: "form-control" %>
  </div>
  <div class="form-group col-md-3 p-3">
    <%= submit_tag "Search", class: "btn btn-info" %>
    <%= link_to 'Reset', products_path, class: "ml-3 btn btn-info" %>
  </div>
<% end %>
<%= form_tag('/export-excel', :method=>'post') do %>
  <div class="form-group col-sm-2" style="margin-top: 2%;">
    <%= hidden_field_tag 'data', @products.to_json %>
    <button class="btn btn-primary" value="submit">Download File</button>
  </div>
<%end%>
</div>
<table  class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Brand</th>
      <th>Year</th>
      <th>Ram</th>
      <th>External storage</th>
      <th>Price</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.model %></td>
        <td><%= product.brand %></td>
        <td><%= product.year %></td>
        <td><%= product.ram %></td>
        <td><%= product.external_storage %></td>
        <td><%= product.price %></td>
        <!-- <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>

</table>
  <%= will_paginate @products %>
<br>
<style type="text/css">
  .previous_page, .next_page{
    border: 1px solid burlywood;
    background-color: burlywood;
    padding: 5px 10px 5px 5px;
  }
  .current{
    border: 1px solid burlywood;
    padding: 5px 10px 5px 10px;
    margin: 0 9px;
    background: #fda83a;
  }
  .pagination a {
    border: 1px solid burlywood;
    padding: 5px 10px 5px 10px;
    margin: 0 9px;
    background-color: burlywood;
  }
</style>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Year:</strong>
  <%= @product.year %>
</p>

<p>
  <strong>Ram:</strong>
  <%= @product.ram %>
</p>

<p>
  <strong>External storage:</strong>
  <%= @product.external_storage %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>